"""Model Ranking configuration (Section 6.6).

The composite ranking score is explicitly required to combine three
independent signals — normalized backtesting metrics, forecast stability and
SHAP/native-importance consistency — so that ranking is never a re-run of
"lowest error wins". Every weight that determines how those signals combine
lives here as a value, never as a literal in the ranking code.

The SHAP/importance signal itself is generated by the Explainability stage
(Section 6.10, `forecast_engine.s07_explainability`) *before* ranking runs —
see `ExplainabilityConfig` for the settings that govern how it is computed.
Ranking only owns how much that already-computed signal counts toward the
composite score.

All three top-level weights are read together and normalized at use time, so
a deployment can express relative emphasis ("stability matters twice as much
as raw accuracy") without needing them to sum to exactly 1.0.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class MetricWeightsConfig:
    """Relative weight of each backtesting metric inside the accuracy score.

    Each metric is first min-max normalized across the candidate models of
    one forecasting group (lower error -> higher normalized score) and then
    combined using these weights. WMAPE carries the largest default weight
    because Section 10 treats it as the platform's primary accuracy measure.
    """

    mape_weight: float = 0.15
    wmape_weight: float = 0.35
    rmse_weight: float = 0.2
    mae_weight: float = 0.15
    smape_weight: float = 0.15


@dataclass(frozen=True)
class StabilityWeightsConfig:
    """Relative weight of each forecast-stability signal (Section 6.6).

    Stability judges the *shape* of the forward forecast, independent of how
    accurate the backtest said the model was — a model can be accurate on
    history and still hand production an erratic or overconfident forecast.
    """

    variance_weight: float = 0.4
    smoothness_weight: float = 0.35
    interval_weight: float = 0.25

    # Score assigned to a model that produces no confidence intervals
    # (every tree model in this phase). Neutral rather than punitive: the
    # model is not unstable, it simply was not asked to quantify uncertainty.
    no_interval_score: float = 0.5


@dataclass(frozen=True)
class CompositeWeightsConfig:
    """Top-level weights combining the three ranking components.

    Normalized at use time, so these express *relative* emphasis rather
    than needing to sum to exactly 1.0.
    """

    backtest_weight: float = 0.5
    stability_weight: float = 0.25
    shap_weight: float = 0.25


@dataclass(frozen=True)
class RankingConfig:
    """Root configuration for Model Ranking (Section 6.6)."""

    metric_weights: MetricWeightsConfig = field(default_factory=MetricWeightsConfig)
    stability_weights: StabilityWeightsConfig = field(default_factory=StabilityWeightsConfig)
    composite_weights: CompositeWeightsConfig = field(default_factory=CompositeWeightsConfig)

    # Return the standard ranking configuration
    @classmethod
    def default(cls) -> "RankingConfig":
        return cls()

    # Build from a nested mapping, ignoring unknown keys
    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "RankingConfig":
        return cls(
            metric_weights=_build_block(MetricWeightsConfig, payload.get("metric_weights")),
            stability_weights=_build_block(StabilityWeightsConfig, payload.get("stability_weights")),
            composite_weights=_build_block(CompositeWeightsConfig, payload.get("composite_weights")),
        )


# Instantiate one config block, keeping only keys it declares
def _build_block(block_type: type, values: dict[str, Any] | None) -> Any:
    if not values:
        return block_type()

    allowed = {f.name for f in block_type.__dataclass_fields__.values()}
    return block_type(**{key: value for key, value in values.items() if key in allowed})
